### ISSUE TITLE
Creating a test issue

### ISSUE THREAD

**Issue by SyedHamzaAzhar** [xaibe/NestJS-App#11]
I'm **creating a test issue** just to learn *how to create an issue*.
-Firstly click the the issues tab and hit the new issue button.
-Then provide a suitable title and start adding the material of concern in the description box.

@xaibe please have a look at the new issue created. And also go through the link attached. Thanks in advance.
![download](https://user-images.githubusercontent.com/85331751/152093364-7d42b92c-56ad-4936-8b51-51adba8a41e6.jpeg)

https://github.com/xaibe/NestJS-App/blob/master/src/auth/controllers/auth.controller.ts#L26-L33
This is the link provided please have look at the code there is something not right. Thanks

**Comment by xaibe** [comment]
### Ok i got it.
@SyedHamzaAzhar 
https://github.com/xaibe/NestJS-App/blob/70be62b4493ec9d6cdf06719a1ca6b36dbeffcad/src/auth/controllers/auth.controller.ts#L31

_**this is the same issue we discussed before i think it will work properly now.**_
